---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-1
  labels:
    app: my-app-1
spec:
  containers:
  - name: my-app-1
    image: my-hello
    imagePullPolicy: Never
    ports:
      - containerPort: 80
    env:
      - name: PORT
        value: '80'
